### ISSUE TITLE
ImportError in prompt_generate_split.py

### ISSUE THREAD

**Issue by mechamaru739** [daochenzha/ltsm#3]
Hi
Thank you for your excellent work on LTSM, which has been very inspiring. I encountered an error when running the following command.
```
python3 prompt_generate_split.py
```
and the error is
<img width="626" alt="image" src="https://github.com/user-attachments/assets/11de3d64-8dac-45b5-952b-5c28f3a02001">

Thank you for your attention to this matter. I look forward to the resolution of this issue.

Best regards

**Comment by guanchuwang** [comment]
Solved.

**Comment by guanchuwang** [comment]
> Hi Thank you for your excellent work on LTSM, which has been very inspiring. I encountered an error when running the following command.
> 
> ```
> python3 prompt_generate_split.py
> ```
> 
> and the error is <img alt="image" width="626" src="https://private-user-images.githubusercontent.com/77657064/351272153-11de3d64-8dac-45b5-952b-5c28f3a02001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDEzNDksIm5iZiI6MTcyMTgwMTA0OSwicGF0aCI6Ii83NzY1NzA2NC8zNTEyNzIxNTMtMTFkZTNkNjQtOGRhYy00NWI1LTk1MmItNWMyOGYzYTAyMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA2MDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmY2Y4YzI5NmFiMjlhNTcwNTZiMDYyOTc5ODljZWVhYWE5NTkzZDk2ZmNiZjNkZWJlYjNjNzdhODRlN2NjYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A1myHnMJSKUNA1xa5vd2x0hUr8wcSLO9lG2LfU-HkyU">
> 
> Thank you for your attention to this matter. I look forward to the resolution of this issue.
> 
> Best regards

Solved.
